import{useEffect,useMemo,useState}from'react';import{Apple,Box,ChevronDown,ChevronUp,Edit3,Home,Minus,PackagePlus,Plus,Search,Settings,Trash2,X}from'lucide-react';

type Unit='unidades'|'pacotes'|'latas'|'garrafas'|'kg'|'g'|'L'|'ml';
type Food={id:string;name:string;quantity:number;unit:Unit};
type Place={id:string;name:string;foods:Food[]};
const initial:Place[]=[{id:'fridge',name:'Geladeira',foods:[]},{id:'freezer',name:'Freezer',foods:[]},{id:'cabinet',name:'Armário',foods:[]},{id:'drawers',name:'Gavetas',foods:[]},{id:'pantry',name:'Despensa',foods:[]}];
const units:Unit[]=['unidades','pacotes','latas','garrafas','kg','g','L','ml'];
const uid=()=>Math.random().toString(36).slice(2,10);

function App(){const[places,setPlaces]=useState<Place[]>(()=>{try{return JSON.parse(localStorage.getItem('organizapp')||'null')||initial}catch{return initial}});const[selected,setSelected]=useState<string|null>(null);const[search,setSearch]=useState('');const[foodModal,setFoodModal]=useState<{place:string;food?:Food}|null>(null);const[placeModal,setPlaceModal]=useState<{place?:Place}|null>(null);
useEffect(()=>localStorage.setItem('organizapp',JSON.stringify(places)),[places]);
const total=places.reduce((n,p)=>n+p.foods.length,0);const current=places.find(p=>p.id===selected);
const results=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return[];return places.flatMap(p=>p.foods.filter(f=>f.name.toLowerCase().includes(q)).map(f=>({...f,place:p.name,placeId:p.id})))},[search,places]);
function saveFood(placeId:string,data:Omit<Food,'id'>,id?:string){setPlaces(ps=>ps.map(p=>p.id!==placeId?p:{...p,foods:id?p.foods.map(f=>f.id===id?{...f,...data}:f):[...p.foods,{...data,id:uid()}]}));setFoodModal(null)}
function removeFood(placeId:string,id:string){setPlaces(ps=>ps.map(p=>p.id===placeId?{...p,foods:p.foods.filter(f=>f.id!==id)}:p))}
function changeQty(placeId:string,id:string,delta:number){setPlaces(ps=>ps.map(p=>p.id===placeId?{...p,foods:p.foods.map(f=>f.id===id?{...f,quantity:Math.max(0,f.quantity+delta)}:f)}:p))}
function savePlace(name:string,id?:string){const clean=name.trim();if(!clean)return;if(id)setPlaces(ps=>ps.map(p=>p.id===id?{...p,name:clean}:p));else setPlaces(ps=>[...ps,{id:uid(),name:clean,foods:[]}]);setPlaceModal(null)}
function removePlace(id:string){setPlaces(ps=>ps.filter(p=>p.id!==id));if(selected===id)setSelected(null)}

return <div className="app"><header><div className="brand"><div className="logo"><Home size={20}/></div><div><h1>OrganizaApp</h1><span>Sua casa, organizada.</span></div></div><button className="icon-btn" onClick={()=>setPlaceModal({})} title="Gerenciar locais"><Settings size={20}/></button></header>
<main>{selected? <section><button className="back" onClick={()=>setSelected(null)}>← Todos os locais</button><div className="section-head"><div><p className="eyebrow">LOCAL</p><h2>{current?.name}</h2><p>{current?.foods.length||0} {current?.foods.length===1?'item':'itens'}</p></div><button className="primary" onClick={()=>setFoodModal({place:selected})}><Plus size={19}/> Adicionar alimento</button></div>{current?.foods.length?<div className="food-list">{current.foods.map(f=><div className="food" key={f.id}><div className="food-icon"><Apple size={19}/></div><div className="food-name"><strong>{f.name}</strong><span>{f.unit}</span></div><div className="qty"><button onClick={()=>changeQty(selected,f.id,-1)}><Minus size={15}/></button><b>{f.quantity}</b><button onClick={()=>changeQty(selected,f.id,1)}><Plus size={15}/></button></div><button className="small" onClick={()=>setFoodModal({place:selected,food:f})}><Edit3 size={17}/></button><button className="small danger" onClick={()=>removeFood(selected,f.id)}><Trash2 size={17}/></button></div>)}</div>:<Empty title="Este local está vazio" text="Adicione os alimentos que estão aqui para manter tudo organizado." action={()=>setFoodModal({place:selected})}/>}</section>
:<section><div className="hero"><div><p className="eyebrow">BEM-VINDO</p><h2>O que você tem em casa?</h2><p>Organize seus alimentos por onde eles ficam e encontre tudo rapidamente.</p></div><div className="total"><span>{total}</span><small>{total===1?'item cadastrado':'itens cadastrados'}</small></div></div><div className="search"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar alimento..."/>{search&&<button onClick={()=>setSearch('')}><X size={17}/></button>}</div>{search?<div className="results">{results.length?results.map(f=><button className="result" key={f.id} onClick={()=>{setSelected(f.placeId);setSearch('')}}><Box size={18}/><span><strong>{f.name}</strong><small>{f.place} · {f.quantity} {f.unit}</small></span><ChevronDown size={16}/></button>):<Empty title="Nenhum alimento encontrado" text="Tente buscar por outro nome."/>}</div>:<><div className="section-title"><h3>Seus locais</h3><button onClick={()=>setPlaceModal({})}><Plus size={17}/> Novo local</button></div><div className="places">{places.map((p,i)=><div className="place-card" key={p.id} onClick={()=>setSelected(p.id)}><div className="place-top"><div className="place-icon"><Box size={21}/></div><div className="arrow">→</div></div><h3>{p.name}</h3><p>{p.foods.length} {p.foods.length===1?'alimento':'alimentos'}</p><div className="progress"><span style={{width:p.foods.length?Math.min(100,p.foods.length*12)+'%':'0%'}}/></div></div>)}</div></>}</section>}</main>
{foodModal&&<FoodModal data={foodModal.food} onClose={()=>setFoodModal(null)} onSave={(d)=>saveFood(foodModal.place,d,foodModal.food?.id)}/>}
{placeModal&&<PlaceModal place={placeModal.place} places={places} onClose={()=>setPlaceModal(null)} onSave={savePlace} onDelete={removePlace}/>}
</div>}

function Empty({title,text,action}:{title:string;text:string;action?:()=>void}){return <div className="empty"><PackagePlus size={30}/><h3>{title}</h3><p>{text}</p>{action&&<button className="primary" onClick={action}><Plus size={18}/> Adicionar alimento</button>}</div>}
function FoodModal({data,onClose,onSave}:{data?:Food;onClose:()=>void;onSave:(d:Omit<Food,'id'>)=>void}){const[name,setName]=useState(data?.name||'');const[quantity,setQuantity]=useState(data?.quantity||1);const[unit,setUnit]=useState<Unit>(data?.unit||'unidades');return <Modal title={data?'Editar alimento':'Novo alimento'} onClose={onClose}><label>Nome do alimento<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Arroz"/></label><div className="row"><label>Quantidade<div className="number"><button onClick={()=>setQuantity(Math.max(0,quantity-1))}><Minus/></button><input type="number" min="0" value={quantity} onChange={e=>setQuantity(Math.max(0,Number(e.target.value)))}/><button onClick={()=>setQuantity(quantity+1)}><Plus/></button></div></label><label>Unidade<select value={unit} onChange={e=>setUnit(e.target.value as Unit)}>{units.map(u=><option key={u}>{u}</option>)}</select></label></div><button className="primary full" disabled={!name.trim()} onClick={()=>onSave({name:name.trim(),quantity,unit})}>{data?'Salvar alterações':'Adicionar alimento'}</button></Modal>}
function PlaceModal({place,places,onClose,onSave,onDelete}:{place?:Place;places:Place[];onClose:()=>void;onSave:(name:string,id?:string)=>void;onDelete:(id:string)=>void}){const[name,setName]=useState(place?.name||'');return <Modal title={place?'Editar local':'Gerenciar locais'} onClose={onClose}>{!place&&<><p className="modal-help">Crie os espaços que fazem sentido na sua casa.</p><div className="manage-list">{places.map(p=><div key={p.id}><span>{p.name}</span><div><button onClick={()=>{onClose();setTimeout(()=>{},0)}}><Edit3 size={16}/></button><button className="danger" onClick={()=>onDelete(p.id)}><Trash2 size={16}/></button></div></div>)}</div></>}<label>{place?'Nome do local':'Novo local'}<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Prateleira da cozinha"/></label><button className="primary full" disabled={!name.trim()} onClick={()=>onSave(name,place?.id)}>{place?'Salvar':'Criar local'}</button></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="overlay" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button onClick={onClose}><X/></button></div>{children}</div></div>}
export default App;